$(function() {
WTF.init({
     heading: [
             "feyral says:"
         ],
         response: [
             "another one!"
     ],
         template: [
             "hello my name is feyral starweaver, your friendly neighborhood @adjective @noun",
             "chat i'm @verb",
             "i'm also the aspect of @noun",
             "ooooh, @noun!",
             "there's some @plural in this house",
             "my chat is full of @plural",
             "we got that hotel motel @noun @noun",
             "you know, like, @noun",
             "i love @plural",
             "give me your @noun",
             "clicking this will take you straight to @noun central",
             "today, i'm going to be @verb",
             "never stop @verb",
             "anyone in chat @verb their @noun",
             "@name what the fuck",
             "an angel is losing her @noun",
              "don't make fun of me i'll start @verb",
        ],
         noun: [
             "love",
             "catgirl",
             "streamer",
             "stinkbug",
             "guh",
             "nya",
             "disaster",
             "meat",
             "pussy",
             "chat",
             "yaoi",
             "minecraft",
             "pokemon",
             "fortnite",
             "boysmell",
             "buh",
             "bean",
         ],
         adjective: [
             "cunty",
             "fucking",
             "wet-ass",
             "certified",
             "gay",
             "submissive",
             "big",
             "zooted",
             "close",
         ],
         verb: [
            "gaming",
            "streaming",
            "slaying",
            "pulling out",
            "jiggling",
            "fucking",
            "jorking it",
            "krunking",
            "flicking",
            "bustin",
            "cumming",
            "singing",
        ],
        plural: [
            "whores",
            "balls",
            "bottoms",
            "boobs",
            "freaks",
            "losers",
            "gays",
        ],
        name: [
            "wrigley",
            "guts",
            "goku",
            "jupiter",
            "chat",
            "roy mustang",
        ],
     });
});
